language: python
python:
  - "2.7"
  - "3.5"
sudo: false
install:
 - mkdir -p buildout-cache/eggs
 - mkdir -p buildout-cache/downloads
 - python bootstrap.py --setuptools-version=33.1.1
 - ./bin/buildout
script:
 - ./bin/test -m birdhousebuilder.recipe.pywps

